contact_links:
  - name: Are you looking for documentation on critical-ai-literacy-in-practice?
    url: https://maehr.github.io/critical-ai-literacy-in-practice
    about: Please see the documentation for critical-ai-literacy-in-practice on its GitHub Pages page.
  - name: Do you want to discuss critical-ai-literacy-in-practice with the community?
    url: https://github.com/maehr/critical-ai-literacy-in-practice/discussions
    about: Please see the discussions page for critical-ai-literacy-in-practice.
blank_issues_enabled: true
